quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/emissions_db
quarkus.datasource.username=root
quarkus.datasource.password=root

quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=true
